name: "cargo clippy"

on:
  push:
    branches:
      - main  
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Protobuf Installation
      - name: Install Protobuf (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
        
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
