name: Rust

on:
  push:     
    branches:
      - main  
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: toolbox - latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      
      # Protobuf Installation
      - name: Install Protobuf (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          
      - name: Install Protobuf (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install protobuf
        
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
